on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: run tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          cd orchestration-lambda
          go test ./... -v -covermode=count

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Calc coverage
        run: |
          make -C orchestration-lambda test
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: 947db02d-7752-41fe-8902-a084b0a8e39a
          file: orchestration-lambda/coverage.txt
          flags: unittests
          name: codecov-umbrella
